services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/site
      - ./node_modules:/site/node_modules
    ports:
      - "4000:4000"
    command: pnpm dev

volumes:
  site:
